CC = gcc
CFLAGS = -std=c99 -g -Wall

all:
	$(CC) $(CFLAGS) -o prob2parta prob2parta.c
	$(CC) $(CFLAGS) -o prob2partb prob2partb.c
	$(CC) $(CFLAGS) -o prob2partc prob2partc.c

clean:
	rm -f prob2parta prob2partb prob2partc
